packages:
  - packages/*
  - playgrounds/*
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@sveltejs/kit@2.68.0'
overrides:
  cookie: ^0.7.2
  esbuild: ^0.28.1
  js-yaml: ^4.2.0
  read-yaml-file: 2.1.0
